{
 "title": "Web-servers count_total and size_bytes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Web-server 2 http_response_count_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "myapp_http_response_count_total{instance=\"192.168.20.19:4040\",method=\"GET\"}"
    }
   ]
  },
  {
   "title": "Web-server 2 http_response_size_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "myapp_http_response_size_bytes{instance=\"192.168.20.19:4040\"}"
    }
   ]
  },
  {
   "title": "Web-server 1 http_response_count_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "myapp_http_response_count_total{instance=\"192.168.10.20:4040\",method=\"GET\"}"
    }
   ]
  },
  {
   "title": "Web-server 1 http_response_size_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "myapp_http_response_size_bytes{instance=\"192.168.10.20:4040\"}"
    }
   ]
  }
 ]
}