---
- hosts: grafana

  tasks:
    - name: Install https://dl.grafana.com/oss/release/grafana_8.3.3_amd64.deb
      apt:
       deb: https://dl.grafana.com/oss/release/grafana_8.3.3_amd64.deb

    - name: Make sure a service is running
      systemd:
        state: started
        name: grafana-server

    - name: enable service tuned and ensure it is not masked
      systemd:
        name: grafana-server
        enabled: yes
        masked: no

  become: yes
  become_method: sudo