---
- hosts: grafana

  tasks:
    - name: Install https://dl.grafana.com/oss/release/grafana_8.3.3_amd64.deb
      apt:
       deb: https://dl.grafana.com/oss/release/grafana_8.3.3_amd64.deb

    - name: Make sure a service is running
      systemd:
        state: started
        name: grafana-server

    - name: enable service tuned and ensure it is not masked
      systemd:
        name: grafana-server
        enabled: yes
        masked: no

    - name: "wait for grafana to come up"
      uri:
        url: "http://192.168.30.33:3000/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: POST from contents of local file
      uri:
        url: https://httpbin.org/post
        method: POST
        src: dashboard.json
  
  become: yes
  become_method: sudo